# PostgreSQL 17
#   gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: kaya_development
  queue:
    <<: *default
    database: kaya_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: kaya_test

# free tier:
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

# paid tier:
# production:
#   primary:
#     <<: *default
#     database: kaya_production
#     url: <%= ENV["DATABASE_URL"] %>
#   cache:
#     <<: *default
#     database: kaya_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *default
#     database: kaya_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *default
#     database: kaya_production_cable
#     migrations_paths: db/cable_migrate
